### ISSUE TITLE
Emojii as habits header

### ISSUE THREAD

**Issue by fabiocodeca** [adamhl8/dataviewjs-habit-tracker#1]
Hi.
Thanks a lot for the code: works perfectly, and it is easy to adapt thanks to all the detailed comments.
I'm wondering if there is a way to substitute the text of the habits name with some emoij. Any clue?

Thanks

**Comment by adamhl8** [comment]
I assume you mean something like this?

![image](https://user-images.githubusercontent.com/1844269/189551308-fe36169c-6841-416b-8520-e479346facdf.png)

If so, right before line 35, you can add something like this:
```
if (habitText === 'Run') habitText = '🏃'
```

Basically you just want to overwrite `habitText` to whatever you want before it's added.

**Comment by fabiocodeca** [comment]
Thanks. That's correct, that solves my need.

I got another question: in order to have the "day of the year" instead of the weekday, which is the code change I need to make? I could not really find any documentation about it on dataview.

**Comment by adamhl8** [comment]
You'd want to replace line 24. ​If you open dev tools in Obsidian (Ctrl+Shift+I) and add `console.log(page.file.day)` to the dataviewjs code block, you can see all the different date related data available to you.

**Comment by adamhl8** [comment]
Feel free to open another issue if you have any questions/concerns.
