### ISSUE TITLE
Feature Request: including the table/ code in Weeklynote

### ISSUE THREAD

**Issue by ritchykemp** [adamhl8/dataviewjs-habit-tracker#2]
Hey @adamhl8, thanks for sharing the code! 
I would like to integrate your table in my weekly-note and my aim would be to show all days of the respective week and not the last 7 days. But I had difficulties to adapt the code, do you have any idea how to change the code?

thanks in advance :)

**Comment by adamhl8** [comment]
Sorry for the slow response. So I'm assuming you have a weekly note _not_ in your Daily Notes folder where the title of that weekly note is the date for the start of the week (e.g. `2022-10-03`).

If so, in your weekly note replace `const pages = ...` (line 13) with the following:
```
const pages = dv
  .pages('"Daily Notes"')
  .where((p) => p.file.day.weekNumber === noteDay.weekNumber)
  .sort((p) => p.file.day, 'desc') // Sort table by most recent day.
  ```

Basically we just get all the pages in Daily Notes that are part of the same week as the weekly note. Let me know if that works for you.
