### ISSUE TITLE
Can you use this code with periodic notes?

### ISSUE THREAD

**Issue by Saorsa32** [adamhl8/dataviewjs-habit-tracker#4]
I would like to be able to use this code with periodic notes. Is there a way to do that? Also, can you use a hashtag instead of the folder to get your daily notes. Thanks

**Comment by adamhl8** [comment]
I haven't used periodic notes before, but I think my reply [here](https://github.com/adamhl8/dataviewjs-habit-tracker/issues/2#issuecomment-1270646295) might point you in the right direction.

> can you use a hashtag instead of the folder to get your daily notes

Sorry, not sure what you mean by this. Can you explain more?
